array oriented programming with numpy


In [ ]:
import numpy as np

In [ ]:
numbers = np.array([1,2,3])

In [ ]:
numbers

array([1, 2, 3])

In [ ]:
new = np.array(range(5))

In [ ]:
new

array([0, 1, 2, 3, 4])

In [ ]:
multi = np.array([[2,3], [4,5]])

In [ ]:
multi

array([[2, 3],
       [4, 5]])

In [ ]:
mutlinew = np.array([[range(2,9,2)],[range(3,13,3)]])

In [ ]:
mutlinew

array([[[ 2,  4,  6,  8]],

       [[ 3,  6,  9, 12]]])

In [ ]:
multinew = np.array([[x for x in range(2,9,2)],[y for y in range(3,13,3)]])

In [ ]:
multinew

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [ ]:
neww= np.array(range(2,4))

In [ ]:
neww

array([2, 3])

In [ ]:
new2 = np.array(range(2,9))

In [ ]:
new2

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
newr = np.array(range(2,9,2))
newr

array([2, 4, 6, 8])

In [ ]:
exe = np.array(range(2,20,2)) # create one dim array that produces even integers from 2 through 20
exe

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
exe2 = np.array([[x for x in range(2,11,2)],[y for y in range(1,10,2)]])
exe2

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [ ]:
floats = np.array([0.0,0.120,0.2]) #does not show 0s
floats

array([0.  , 0.12, 0.2 ])

In [ ]:
floats.dtype

exe.dtype

dtype('int64')

In [ ]:
exe2.ndim

2

In [ ]:
floats.ndim

1

In [ ]:
floats.shape

(3,)

In [ ]:
exe2.shape

(2, 5)

In [ ]:
exe2.size

10

In [ ]:
for row in exe2:
    for col in row:
        print(col, end=' ')
    print()

2 4 6 8 10 
1 3 5 7 9 


In [ ]:
for i in exe2.flat:
    print(i, end=' ')

2 4 6 8 10 1 3 5 7 9 

In [ ]:
exe2

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

filling arrays with specific value

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
newfilled= np.zeros(6)
newfilled

array([0., 0., 0., 0., 0., 0.])

In [ ]:
ey =np.full((5,7),6)

In [ ]:
ey.dtype
newfilled.dtype

dtype('float64')

creating arrays from ranges

In [ ]:
np.arange(5) # 0 1 2 3 4 5

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5,10) # 5 6 7 8 9 !!!!!!10 İS NOT İNCLUDED.

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10,2) # 5 7 9

array([5, 7, 9])

In [ ]:
np.arange(5,10,0.5) # 5 5.5 6 6.5 7 7.5 8 8.5 9 9.5

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.linspace(0.0,1.0, num = 5) # 5 evenly spaced numbers from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.arange(2,41,2).reshape(4,5) #ex create an array of 20 integers from 2 through 40, then resahpe it 4 by 5 array

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [ ]:
nums = np.arange(1,6)

In [ ]:
nums

array([1, 2, 3, 4, 5])

In [ ]:
nums *2

array([ 2,  4,  6,  8, 10])

In [ ]:
nums

array([1, 2, 3, 4, 5])

In [ ]:
nums **2

array([ 1,  4,  9, 16, 25])

In [ ]:
nums >3

array([False, False, False,  True,  True])

In [ ]:
newwww= np.arange(1,6)

In [ ]:
newwww **2

array([ 1,  4,  9, 16, 25])

In [ ]:
  newwww

array([1, 2, 3, 4, 5])

In [ ]:
newwww.sum()

15

In [ ]:
exe2

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [ ]:
exe2.mean()

5.5

In [ ]:
exe2.mean(axis=0)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [ ]:
exe2.mean(axis=1)

array([6., 5.])

In [ ]:
helo = np.arange(2,7)

In [ ]:
helo

array([2, 3, 4, 5, 6])

In [ ]:
helo + newwww

array([ 3,  5,  7,  9, 11])

selecting a subset of 2d arrays

In [ ]:
hey = np.arange(1,10).reshape(3,3)

In [ ]:
hey

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
hey[0]

array([1, 2, 3])

In [ ]:
hey[1]

array([4, 5, 6])

In [ ]:
hey[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
hey[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
hey[:,1]

array([2, 5, 8])

In [ ]:
hey[:,2]

array([3, 6, 9])

In [ ]:
hey[:,1:3] l

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
hey[:,[0,2] ]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
helloo = np.array(range(1,7)).resize(2,3)

In [ ]:
helloo

In [ ]:
hi=np.array(range(1,7)).reshape(2,3)

In [ ]:
hi= np.hstack((hi,hi))

In [ ]:

hi=np.vstack((hi,hi))

In [ ]:
hi

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

pandas - series 1dim, dataframes 2dim
numpy does not support mixed data types but pandas supports.

In [ ]:
import pandas as pd

In [ ]:
eylul = pd.Series([2,4,6])

In [ ]:
eylul

0    2
1    4
2    6
dtype: int64

In [ ]:
eylul2 = pd.Series(12, range(1,6)) #second argument contains the series's indices. creating a series with a value 6.

In [ ]:
eylul2

1    12
2    12
3    12
4    12
5    12
dtype: int64

In [ ]:
eylul[1]

4

In [ ]:
eylul.mean()

4.0

In [ ]:
eylul.count()

3

In [ ]:
eylul.describe()

count    3.0
mean     4.0
std      2.0
min      2.0
25%      3.0
50%      4.0
75%      5.0
max      6.0
dtype: float64

In [ ]:
newseries = pd.Series([12,23,22], index=['a','b','c'])

In [ ]:
newseries

a    12
b    23
c    22
dtype: int64

In [ ]:
newseries['a']

12

In [ ]:
newseries.values

array([12, 23, 22])

In [ ]:
newseries.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
newseriesq = pd.Series(['hello girls','pırt','denemea'], index=['a','b','c'])

In [ ]:
newseriesq

a    hello girls
b           pırt
c        denemea
dtype: object

In [ ]:
newseriesq.str.contains('a')

a    False
b    False
c     True
dtype: bool

In [ ]:
newseriesq.index = ["first","second","third"]

In [ ]:
newseriesq

first     hello girls
second           pırt
third         denemea
dtype: object

**DATAFRAME**

In [ ]:
grads = pd.DataFrame({'Eylul': [1,2,3], 'Ekin': [3,4,5]})

In [ ]:
grads

Eylul  Ekin
0      1     3
1      2     4
2      3     5

In [ ]:
grads.index = ["first","second","third"]

In [ ]:
grads

Eylul  Ekin
first       1     3
second      2     4
third       3     5

In [ ]:
grads['Eylul']

first     1
second    2
third     3
Name: Eylul, dtype: int64

selecting rows via loc and iloc attributes

In [ ]:
grads.loc['first'] #with row named first is accessed with the values

Eylul    1
Ekin     3
Name: first, dtype: int64

In [ ]:
grads.iloc[2] #with row index 2 is accessed with the values

Eylul    3
Ekin     5
Name: third, dtype: int64

In [ ]:
grads.iloc[1] # column name - value

Eylul    2
Ekin     4
Name: second, dtype: int64

selecting rows via slices and lists with the loc and iloc attributes

In [ ]:
grads.loc['first':'second'] # includes the high index

Eylul  Ekin
first       1     3
second      2     4

In [ ]:
grads.iloc[0:2] #excludes the high index

Eylul  Ekin
first       1     3
second      2     4

In [ ]:
grads.loc[['first','third']] #selecting specific rows with a list

Eylul  Ekin
first      1     3
third      3     5

In [ ]:
grads.iloc[[0,2]] #selecting specific rows with a list

Eylul  Ekin
first      1     3
third      3     5

In [ ]:
grads.loc['first':'third','Eylul'] #selecting specific rows and columns

first     1
second    2
third     3
Name: Eylul, dtype: int64

In [ ]:
grads.iloc[0:2,0:2] #selecting specific rows and columns

Eylul  Ekin
first       1     3
second      2     4

In [ ]:
grads[grads > 1] #boolean indexing

Eylul  Ekin
first     NaN     3
second    2.0     4
third     3.0     5

Accessing a Specific DataFrame Cell by Row and Column

In [ ]:
grads.at['second','Eylul'] #second row, eylul column

2

In [ ]:
grads.iat[2,0] #third row, eylul column

3

In [ ]:
grads.describe()

Eylul  Ekin
count    3.0   3.0
mean     2.0   4.0
std      1.0   1.0
min      1.0   3.0
25%      1.5   3.5
50%      2.0   4.0
75%      2.5   4.5
max      3.0   5.0

In [ ]:
grads.T.describe() #transpose

first    second     third
count  2.000000  2.000000  2.000000
mean   2.000000  3.000000  4.000000
std    1.414214  1.414214  1.414214
min    1.000000  2.000000  3.000000
25%    1.500000  2.500000  3.500000
50%    2.000000  3.000000  4.000000
75%    2.500000  3.500000  4.500000
max    3.000000  4.000000  5.000000

In [ ]:
grads.sort_index(ascending=False) #descending order

Eylul  Ekin
third       3     5
second      2     4
first       1     3

In [ ]:
grads.sort_index(axis=1) #sort columns in ascending order.

Ekin  Eylul
first      3      1
second     4      2
third      5      3

In [ ]:
grads.sort_values(by='first', axis=1, ascending =True) #sort values in ascending order

Eylul  Ekin
first       1     3
second      2     4
third       3     5

In [ ]:
grads.loc['first']

Eylul    1
Ekin     3
Name: first, dtype: int64

In [ ]:
grads.loc['first'].sort_values(ascending=False) #sort values in descending order.

Ekin     3
Eylul    1
Name: first, dtype: int64

örnek

In [ ]:
temps = {'Mon': [68,99], 'Tue': [71,93], 'Wed': [66,82], 'Thu': [75,97], 'Fri': [62,89]}

In [ ]:
temperatures = pd.DataFrame(temps,index =['Low', 'High'])

In [ ]:
temperatures

Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   99   93   82   97   89

In [ ]:
temperatures.loc[:,'Mon':'Wed'] #use column names to select only only the columns mon through wed. COLUMNS

Mon  Tue  Wed
Low    68   71   66
High   99   93   82

In [ ]:
temperatures.loc['Low'] #select only the rows with low temperatures ROWS

Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: Low, dtype: int64

In [ ]:
#pd.set_option('precision',2) #set the floating-point precision to 2 decimal places

In [ ]:
temperatures.describe()

Mon        Tue        Wed        Thu        Fri
count   2.00000   2.000000   2.000000   2.000000   2.000000
mean   83.50000  82.000000  74.000000  86.000000  75.500000
std    21.92031  15.556349  11.313708  15.556349  19.091883
min    68.00000  71.000000  66.000000  75.000000  62.000000
25%    75.75000  76.500000  70.000000  80.500000  68.750000
50%    83.50000  82.000000  74.000000  86.000000  75.500000
75%    91.25000  87.500000  78.000000  91.500000  82.250000
max    99.00000  93.000000  82.000000  97.000000  89.000000

In [ ]:
temperatures.T.describe()

Low      High
count   5.000000   5.00000
mean   68.400000  92.00000
std     4.929503   6.78233
min    62.000000  82.00000
25%    66.000000  89.00000
50%    68.000000  93.00000
75%    71.000000  97.00000
max    75.000000  99.00000

In [ ]:
temperatures.mean()

Mon    83.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    75.5
dtype: float64

In [ ]:
temperatures.mean(axis=1)

Low     68.4
High    92.0
dtype: float64

In [ ]:
temperatures.mean(axis=0)

Mon    83.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    75.5
dtype: float64

\